FROM python:3.7-slim
RUN mkdir -p /usr/local/http-server
RUN useradd runner -d /home/runner -m -s /bin/bash
WORKDIR /usr/local/http-server
ADD ./index.html ./application.py /usr/local/http-server/application.py
RUN chown -R runner:runner /usr/local/http-server/
EXPOSE 9000
USER runner
CMD ["python3", "-u", "/usr/local/http-server/application.py"]

