apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-psu
  labels:
    app: devops-psu
    release-date: 1751120813
  namespace: devops-psu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-psu
  template:
    metadata:
      labels:
        app: devops-psu
        svc: frontend
        release-date: 1751120813
    spec:
      containers:
        - name: devops-psu-server
          image: dd9f92b2bbac/devops-psu:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service-devops
  labels:
    app: devops-psu
  namespace: devops-psu
spec:
  type: LoadBalancer
  selector:
    app: devops-psu
    svc: frontend
  ports:
    - port: 12345
      targetPort: 8000
  externalIPs:
    - 192.168.88.129
